### ISSUE TITLE
Yeni işletme talebi screen alert problems 

### ISSUE THREAD

**Issue by Muratcancftc** [VB-CORE/life_shared#49]
Ekrana girip direkt talep oluştur dedikten sonra zorunlu textler uyarı vermektedir. En alta scroll ile gidip son yukarı çıktığımızda bu uyarı  ad soyad ve telefon numarası girinizden kalkmaktadır. 
https://github.com/VB-CORE/life_shared/assets/107050541/0208559d-5252-432c-9a98-d6495cff6829

**Comment by burakJs** [comment]
Done ✅

**Comment by Muratcancftc** [comment]
@burakJs eline sağlık başkanım
