### ISSUE TITLE
Yeni proje talebi screen alert problems 

### ISSUE THREAD

**Issue by Muratcancftc** [VB-CORE/life_shared#50]
Yeni işletme talebi ekranında, KVKK onayı yapılmadan butona basıldığında boş olan metin alanları için "boş olamaz" uyarısı verilmekte. Ancak, yeni proje talebi ekranında butona bastığımızda herhangi bir aksiyon veya uyarı alınmıyor ve textler boşken buton aktif gözükmekte. KVKK onayı yapıldıktan sonra butona basıldığında ise boş olan metin alanları için uyarılar gösterilmektedir.

**Comment by burakJs** [comment]
Done ✅

**Comment by Muratcancftc** [comment]
@burakJs eline sağlık hocam
