### ISSUE TITLE
Yeni Burs Talebi Screen

### ISSUE THREAD

**Issue by Muratcancftc** [VB-CORE/life_shared#51]
Yeni burs talebi ekranında telefo numarası texti numeric gelmemektedir 
<img src="https://github.com/VB-CORE/life_shared/assets/107050541/0acb29c6-b27e-411d-b305-c5b2444540fd" alt="482b8dc4-3615-43d0-a394-8aa5c4bd776f" width="150" />

**Comment by Muratcancftc** [comment]
@BerkSartik durum nedir hocam bilgi verebilir misin

**Comment by BerkSartik** [comment]
https://github.com/VB-CORE/life_client/pull/273 done

**Comment by Muratcancftc** [comment]
@BerkSartik eline sağlık
